import { createHmac } from 'node:crypto';
import { describe, expect, it } from 'vitest';
import { isValidTwilioSignature, twilioSignatureBase } from './signature';

/**
 * Twilio's OWN published example (twilio.com/docs/usage/security). It is the point of
 * this file: a vector generated by our own `computeTwilioSignature` would pass even if
 * the concatenation order, the hash, or the encoding were wrong. This one fails unless
 * all three match Twilio's scheme exactly.
 */
const DOC_TOKEN = '12345';
const DOC_URL = 'https://example.com/myapp.php?foo=1&bar=2';
const DOC_PARAMS = {
  CallSid: 'CA1234567890ABCDE',
  Caller: '+14158675310',
  Digits: '1234',
  From: '+14158675310',
  To: '+18005551212',
};
const DOC_SIGNATURE = 'L/OH5YylLD5NRKLltdqwSvS0BnU=';

/** Sign the Twilio way, written from the spec rather than by calling the module under
 * test — so a bug in the module cannot make its own fixtures agree with it. */
function signLikeTwilio(token: string, url: string, params: Record<string, string>): string {
  let base = url;
  for (const key of Object.keys(params).sort()) {
    base += key + params[key];
  }
  return createHmac('sha1', token).update(base, 'utf8').digest('base64');
}

const TOKEN = 'test_auth_token_abc123';
const URL_HALE = 'https://app.villagehale.com/api/channels/twilio/inbound';
const PARAMS = {
  AccountSid: 'AC00000000000000000000000000000000',
  Body: 'two kids, 3 and 6, M4B',
  From: '+14165551234',
  MessageSid: 'SM11111111111111111111111111111111',
  To: '+14165550000',
};

describe('twilioSignatureBase', () => {
  it('appends key+value pairs sorted by key, with no delimiters', () => {
    expect(twilioSignatureBase(DOC_URL, DOC_PARAMS)).toBe(
      'https://example.com/myapp.php?foo=1&bar=2CallSidCA1234567890ABCDECaller+14158675310Digits1234From+14158675310To+18005551212',
    );
  });

  it('sorts case-sensitively (Unix order), so uppercase keys precede lowercase', () => {
    expect(twilioSignatureBase('https://x.test/', { a: '1', B: '2' })).toBe('https://x.test/B2a1');
  });
});

describe('isValidTwilioSignature', () => {
  it("accepts Twilio's published example signature", () => {
    expect(
      isValidTwilioSignature({
        authToken: DOC_TOKEN,
        url: DOC_URL,
        params: DOC_PARAMS,
        signature: DOC_SIGNATURE,
      }),
    ).toBe(true);
  });

  it('accepts a well-formed signature over our own webhook URL', () => {
    expect(
      isValidTwilioSignature({
        authToken: TOKEN,
        url: URL_HALE,
        params: PARAMS,
        signature: signLikeTwilio(TOKEN, URL_HALE, PARAMS),
      }),
    ).toBe(true);
  });

  it('rejects a TAMPERED parameter value (body rewritten after signing)', () => {
    const signature = signLikeTwilio(TOKEN, URL_HALE, PARAMS);
    expect(
      isValidTwilioSignature({
        authToken: TOKEN,
        url: URL_HALE,
        params: { ...PARAMS, Body: 'STOP' },
        signature,
      }),
    ).toBe(false);
  });

  it('rejects a tampered SENDER (From swapped to another number)', () => {
    const signature = signLikeTwilio(TOKEN, URL_HALE, PARAMS);
    expect(
      isValidTwilioSignature({
        authToken: TOKEN,
        url: URL_HALE,
        params: { ...PARAMS, From: '+14165559999' },
        signature,
      }),
    ).toBe(false);
  });

  it('rejects an ADDED parameter the signature never covered', () => {
    const signature = signLikeTwilio(TOKEN, URL_HALE, PARAMS);
    expect(
      isValidTwilioSignature({
        authToken: TOKEN,
        url: URL_HALE,
        params: { ...PARAMS, NumMedia: '1' },
        signature,
      }),
    ).toBe(false);
  });

  it('rejects a URL MISMATCH — a signature for one endpoint replayed at another', () => {
    const signature = signLikeTwilio(
      TOKEN,
      'https://app.villagehale.com/api/channels/twilio/status',
      PARAMS,
    );
    expect(
      isValidTwilioSignature({ authToken: TOKEN, url: URL_HALE, params: PARAMS, signature }),
    ).toBe(false);
  });

  it('rejects a signature captured from a DIFFERENT request (cross-request replay)', () => {
    const other = signLikeTwilio(TOKEN, URL_HALE, {
      ...PARAMS,
      MessageSid: 'SM22222222222222222222222222222222',
    });
    expect(
      isValidTwilioSignature({ authToken: TOKEN, url: URL_HALE, params: PARAMS, signature: other }),
    ).toBe(false);
  });

  it('rejects a signature made with a different auth token', () => {
    expect(
      isValidTwilioSignature({
        authToken: TOKEN,
        url: URL_HALE,
        params: PARAMS,
        signature: signLikeTwilio('some_other_token', URL_HALE, PARAMS),
      }),
    ).toBe(false);
  });

  it('rejects a missing or empty signature header', () => {
    for (const signature of [null, '']) {
      expect(isValidTwilioSignature({ authToken: TOKEN, url: URL_HALE, params: PARAMS, signature }))
        .toBe(false);
    }
  });

  it('rejects a malformed signature of the wrong length rather than throwing', () => {
    expect(
      isValidTwilioSignature({
        authToken: TOKEN,
        url: URL_HALE,
        params: PARAMS,
        signature: 'not-base64',
      }),
    ).toBe(false);
  });
});
