import type { PassportModel } from '~/lib/passport/read';

const MIA = 'preview-mia';
const LEO = 'preview-leo';

export function previewPassport(): PassportModel {
  return {
    preview: true,
    shareWithGroup: false,
    members: [
      { name: 'Sam (you)', detail: 'Full access' },
      { name: 'Jordan', detail: 'Co-parent · full access' },
      { name: 'Grandma Lin', detail: 'Caregiver · pickups only' },
    ],
    children: [
      kid(
        MIA,
        'Mia',
        'her',
        'Age 7 · Grade 2',
        'Age 7',
        'Born March 2019',
        'Grade 2',
        '3:20',
        'Nut allergy. Shy for the first ten minutes.',
        miaStamps(),
      ),
      kid(
        LEO,
        'Leo',
        'his',
        'Age 4 · Daycare',
        'Age 4',
        'Born June 2022',
        'Daycare',
        null,
        null,
        leoStamps(),
      ),
    ],
    unassigned: [],
  };
}

function kid(
  id: string,
  name: string,
  pronoun: 'her' | 'his',
  meta: string,
  age: string,
  born: string,
  grade: string | null,
  schoolDayEnds: string | null,
  notes: string | null,
  stamps: PassportModel['children'][number]['stamps'],
): PassportModel['children'][number] {
  return { id, name, pronoun, meta, age, born, grade, schoolDayEnds, notes, stamps, removed: [] };
}

function stamp(
  partial: PassportModel['children'][number]['stamps'][number],
): PassportModel['children'][number]['stamps'][number] {
  return partial;
}

function miaStamps(): PassportModel['children'][number]['stamps'] {
  return [
    stamp({
      id: 'preview-soccer',
      childId: MIA,
      activity: 'Soccer',
      level: null,
      kind: 'activity',
      state: 'confirmed',
      shared: false,
      sourceLabel: 'Gmail receipt · confirmed by you',
      sourceDetail: null,
      emailUrl: null,
      progress: 'Spring · 8 of 12 weeks',
      face: 'APR 26',
      whenLabel: 'Saturdays',
      icon: 'soccer',
      inferred: false,
      top: 'SOCCER',
    }),
    stamp({
      id: 'preview-swimming',
      childId: MIA,
      activity: 'Swimming',
      level: null,
      kind: 'activity',
      state: 'confirmed',
      shared: false,
      sourceLabel: 'Weekly Calendar event · confirmed',
      sourceDetail: null,
      emailUrl: null,
      progress: 'Winter · complete',
      face: 'JAN 26',
      whenLabel: null,
      icon: 'swimming',
      inferred: false,
      top: 'SWIMMING',
    }),
    stamp({
      id: 'preview-skating',
      childId: MIA,
      activity: 'Skating',
      level: null,
      kind: 'activity',
      state: 'confirmed',
      shared: false,
      sourceLabel: 'You told Hale · Dec 3',
      sourceDetail: null,
      emailUrl: null,
      progress: 'Winter · complete',
      face: 'DEC 25',
      whenLabel: null,
      icon: 'skating',
      inferred: false,
      top: 'SKATING',
    }),
    stamp({
      id: 'preview-zoo',
      childId: MIA,
      activity: 'Zoo Day',
      level: null,
      kind: 'outing',
      state: 'confirmed',
      shared: false,
      sourceLabel: 'You told Hale · Aug 17',
      sourceDetail: null,
      emailUrl: null,
      progress: null,
      face: 'AUG 25',
      whenLabel: null,
      icon: 'zoo',
      inferred: false,
      top: 'ZOO DAY',
    }),
    stamp({
      id: 'preview-karate',
      childId: MIA,
      activity: 'Karate',
      level: 'White belt',
      kind: 'activity',
      state: 'inferred',
      shared: false,
      sourceLabel: 'Seen in your Gmail receipt',
      sourceDetail: '“Registration confirmed: Little Dragons Karate, Fall session” · Sep 2',
      emailUrl: 'https://mail.google.com/mail/u/0/#all/preview-karate',
      progress: 'Fall 2026',
      face: 'SEP 26',
      whenLabel: 'Fall 2026 · Saturdays',
      icon: 'karate',
      inferred: true,
      top: 'KARATE',
    }),
    stamp({
      id: 'preview-aquarium',
      childId: MIA,
      activity: 'Aquarium',
      level: null,
      kind: 'outing',
      state: 'confirmed',
      shared: false,
      sourceLabel: 'Calendar event · confirmed',
      sourceDetail: null,
      emailUrl: null,
      progress: null,
      face: 'JUL 25',
      whenLabel: null,
      icon: 'aquarium',
      inferred: false,
      top: 'AQUARIUM',
    }),
    stamp({
      id: 'preview-ballet',
      childId: MIA,
      activity: 'Ballet',
      level: 'Pre-primary',
      kind: 'activity',
      state: 'inferred',
      shared: false,
      sourceLabel: 'Weekly Calendar event',
      sourceDetail: null,
      emailUrl: null,
      progress: 'Fall 2026',
      face: 'OCT 26',
      whenLabel: 'Fall 2026',
      icon: 'ballet',
      inferred: true,
      top: 'BALLET',
    }),
    stamp({
      id: 'preview-farm',
      childId: MIA,
      activity: 'Farm',
      level: null,
      kind: 'outing',
      state: 'confirmed',
      shared: true,
      sourceLabel: "Shared by Priya's family (opted in)",
      sourceDetail: null,
      emailUrl: null,
      progress: null,
      face: 'SEP 25',
      whenLabel: null,
      icon: 'farm',
      inferred: false,
      top: 'FARM',
    }),
  ];
}

function leoStamps(): PassportModel['children'][number]['stamps'] {
  return [
    stamp({
      id: 'preview-leo-hockey',
      childId: LEO,
      activity: 'Hockey',
      level: null,
      kind: 'activity',
      state: 'confirmed',
      shared: false,
      sourceLabel: 'You told Hale · Jan 12',
      sourceDetail: null,
      emailUrl: null,
      progress: 'Winter · complete',
      face: 'JAN 26',
      whenLabel: null,
      icon: 'hockey',
      inferred: false,
      top: 'HOCKEY',
    }),
    stamp({
      id: 'preview-leo-basketball',
      childId: LEO,
      activity: 'Basketball',
      level: null,
      kind: 'activity',
      state: 'confirmed',
      shared: false,
      sourceLabel: 'Weekly Calendar event · confirmed',
      sourceDetail: null,
      emailUrl: null,
      progress: 'Spring · 4 of 8 weeks',
      face: 'APR 26',
      whenLabel: null,
      icon: 'basketball',
      inferred: false,
      top: 'BASKETBALL',
    }),
    stamp({
      id: 'preview-leo-dance',
      childId: LEO,
      activity: 'Dance',
      level: null,
      kind: 'activity',
      state: 'confirmed',
      shared: false,
      sourceLabel: 'Gmail receipt · confirmed by you',
      sourceDetail: null,
      emailUrl: null,
      progress: 'Fall · complete',
      face: 'OCT 25',
      whenLabel: null,
      icon: 'dance',
      inferred: false,
      top: 'DANCE',
    }),
  ];
}
