import type { GtaRegion, SocialCategory, SocialPlatform } from '@hale/db';

/**
 * VIL-378 — curated GTA watchlist.
 *
 * Handles were read off a public page on 2026-09-27 (the sourceUrl): the
 * organization's own site, a municipal homepage, or the Kids Pass
 * directory card that links the handle. Instagram is stored lowercase.
 * active false means the handle was named but the city was not on that
 * page, so it is not polled. Facebook pages wait on PPCA. Nothing here
 * is a Story, a Xiaohongshu note, or a scrape.
 */
export interface SocialSeedSource {
  platform: SocialPlatform;
  handle: string;
  displayName: string;
  city: string | null;
  region: GtaRegion;
  category: SocialCategory;
  fsa: string | null;
  sourceUrl: string;
  active: boolean;
  note: string;
}

export const SOCIAL_SEED: readonly SocialSeedSource[] = [
  {
    platform: 'instagram',
    handle: 'acton_georgetownearlyon',
    displayName: 'Acton and Georgetown EarlyON',
    city: 'Acton',
    region: 'halton',
    category: 'T1',
    fsa: 'L7J',
    sourceUrl: 'https://www.links2care.ca/programs/earlyon/',
    active: true,
    note: 'Handle linked on the Links2Care EarlyON page, 2026-09-27. Acton postal L7J.',
  },
  {
    platform: 'instagram',
    handle: 'links2care',
    displayName: 'Links2Care',
    city: 'Georgetown',
    region: 'halton',
    category: 'T1',
    fsa: 'L7G',
    sourceUrl: 'https://www.links2care.ca/',
    active: true,
    note: 'Org homepage linked this handle. Contact page lists Georgetown L7G.',
  },
  {
    platform: 'facebook_page',
    handle: 'links2care',
    displayName: 'Links2Care',
    city: 'Georgetown',
    region: 'halton',
    category: 'T1',
    fsa: 'L7G',
    sourceUrl: 'https://www.links2care.ca/',
    active: true,
    note: 'Facebook page linked on the org homepage. Poll waits on PPCA.',
  },
  {
    platform: 'facebook_page',
    handle: 'earlyyears',
    displayName: 'Acton EarlyON',
    city: 'Acton',
    region: 'halton',
    category: 'T1',
    fsa: 'L7J',
    sourceUrl: 'https://www.links2care.ca/programs/earlyon/',
    active: true,
    note: 'Facebook page linked beside the Acton EarlyON program. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'mcrchalton',
    displayName: 'Milton Community Resource Centre',
    city: 'Milton',
    region: 'halton',
    category: 'T1',
    fsa: 'L9T',
    sourceUrl: 'https://mcrc.on.ca/earlyon',
    active: true,
    note: 'EarlyON page linked this handle. Site lists Milton L9T.',
  },
  {
    platform: 'instagram',
    handle: 'mcrc_earlyon_and_family_fun',
    displayName: 'MCRC EarlyON and Family Fun',
    city: 'Milton',
    region: 'halton',
    category: 'T1',
    fsa: 'L9T',
    sourceUrl: 'https://mcrc.on.ca/earlyon',
    active: true,
    note: 'Second handle on the same EarlyON page.',
  },
  {
    platform: 'facebook_page',
    handle: 'mcrchalton',
    displayName: 'Milton Community Resource Centre',
    city: 'Milton',
    region: 'halton',
    category: 'T1',
    fsa: 'L9T',
    sourceUrl: 'https://mcrc.on.ca/earlyon',
    active: true,
    note: 'Facebook page on the EarlyON page. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'thehaltonresourceconnection',
    displayName: 'The Halton Resource Connection',
    city: 'Milton',
    region: 'halton',
    category: 'T1',
    fsa: 'L9T',
    sourceUrl: 'https://thrc.ca/',
    active: true,
    note: 'Homepage linked this handle. Milton L9T.',
  },
  {
    platform: 'facebook_page',
    handle: 'thehaltonresourceconnection',
    displayName: 'The Halton Resource Connection',
    city: 'Milton',
    region: 'halton',
    category: 'T1',
    fsa: 'L9T',
    sourceUrl: 'https://thrc.ca/',
    active: true,
    note: 'Facebook page on the homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'oakvilleparentchildcentre',
    displayName: 'Oakville Parent-Child Centre',
    city: 'Oakville',
    region: 'halton',
    category: 'T1',
    fsa: null,
    sourceUrl: 'https://thrc.ca/earlyon-locations/',
    active: true,
    note: 'Listed on the Halton EarlyON locations page.',
  },
  {
    platform: 'facebook_page',
    handle: 'oakvilleparentchildcentre',
    displayName: 'Oakville Parent-Child Centre',
    city: 'Oakville',
    region: 'halton',
    category: 'T1',
    fsa: null,
    sourceUrl: 'https://thrc.ca/earlyon-locations/',
    active: true,
    note: 'Facebook page on the Halton EarlyON locations page. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'rockreachout',
    displayName: 'Rock Reach Out EarlyON',
    city: 'Halton',
    region: 'halton',
    category: 'T1',
    fsa: null,
    sourceUrl: 'https://thrc.ca/earlyon-locations/',
    active: true,
    note: 'Listed on the Halton EarlyON locations page.',
  },
  {
    platform: 'facebook_page',
    handle: 'rockearlyon',
    displayName: 'Rock EarlyON',
    city: 'Halton',
    region: 'halton',
    category: 'T1',
    fsa: null,
    sourceUrl: 'https://thrc.ca/earlyon-locations/',
    active: true,
    note: 'Facebook page on the Halton EarlyON locations page. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'bgchamhal',
    displayName: 'BGC Halton',
    city: 'Burlington',
    region: 'halton',
    category: 'T1',
    fsa: 'L8H',
    sourceUrl: 'https://www.bgchh.com/earlyon',
    active: true,
    note: 'EarlyON page linked this handle. Page lists Burlington FSAs L8H-L8M.',
  },
  {
    platform: 'facebook_page',
    handle: 'bgchamhal',
    displayName: 'BGC Halton',
    city: 'Burlington',
    region: 'halton',
    category: 'T1',
    fsa: 'L8H',
    sourceUrl: 'https://www.bgchh.com/earlyon',
    active: true,
    note: 'Facebook page on the EarlyON page. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'bridgewayfamilycentre',
    displayName: 'BridgeWay Family Centre',
    city: 'Mississauga',
    region: 'peel',
    category: 'T1',
    fsa: null,
    sourceUrl: 'https://bridgewaycentre.ca/',
    active: true,
    note: 'Homepage linked this handle on 2026-09-27 and names Mississauga. A later fetch of the same URL did not repeat the link.',
  },
  {
    platform: 'instagram',
    handle: 'mydbnc',
    displayName: 'Dixie Bloor Neighbourhood Centre',
    city: 'Mississauga',
    region: 'peel',
    category: 'T1',
    fsa: 'L4Y',
    sourceUrl: 'https://www.dixiebloor.ca/',
    active: true,
    note: 'Homepage linked this handle. Contact page lists Mississauga L4Y.',
  },
  {
    platform: 'facebook_page',
    handle: 'mydbnc',
    displayName: 'Dixie Bloor Neighbourhood Centre',
    city: 'Mississauga',
    region: 'peel',
    category: 'T1',
    fsa: 'L4Y',
    sourceUrl: 'https://www.dixiebloor.ca/',
    active: true,
    note: 'Facebook page on the homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'mnsmalton',
    displayName: 'Malton Neighbourhood Services',
    city: 'Mississauga',
    region: 'peel',
    category: 'T1',
    fsa: 'L4T',
    sourceUrl: 'https://mnsinfo.org/',
    active: true,
    note: 'Homepage linked this handle. Contact page lists Mississauga L4T.',
  },
  {
    platform: 'instagram',
    handle: 'cdi_toronto',
    displayName: 'Child Development Institute',
    city: 'Toronto',
    region: 'toronto',
    category: 'T1',
    fsa: null,
    sourceUrl: 'https://www.childdevelop.ca/',
    active: true,
    note: 'Homepage linked this handle. Page names Toronto.',
  },
  {
    platform: 'facebook_page',
    handle: 'childdevelop',
    displayName: 'Child Development Institute',
    city: 'Toronto',
    region: 'toronto',
    category: 'T1',
    fsa: null,
    sourceUrl: 'https://www.childdevelop.ca/',
    active: true,
    note: 'Facebook page on the homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'westnh',
    displayName: 'West Neighbourhood House',
    city: 'Toronto',
    region: 'toronto',
    category: 'T1',
    fsa: null,
    sourceUrl: 'https://westnh.org/',
    active: true,
    note: 'Homepage linked this handle. Page names Toronto.',
  },
  {
    platform: 'facebook_page',
    handle: 'westneighbourhoodhouse',
    displayName: 'West Neighbourhood House',
    city: 'Toronto',
    region: 'toronto',
    category: 'T1',
    fsa: null,
    sourceUrl: 'https://westnh.org/',
    active: true,
    note: 'Facebook page on the homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'nativechildoftoronto',
    displayName: 'Native Child and Family Services of Toronto',
    city: 'Toronto',
    region: 'toronto',
    category: 'T1',
    fsa: null,
    sourceUrl: 'https://www.nativechild.org/',
    active: true,
    note: 'Homepage linked this handle. Page names Toronto.',
  },
  {
    platform: 'facebook_page',
    handle: 'nativechildandfamily',
    displayName: 'Native Child and Family Services of Toronto',
    city: 'Toronto',
    region: 'toronto',
    category: 'T1',
    fsa: null,
    sourceUrl: 'https://www.nativechild.org/',
    active: true,
    note: 'Facebook page on the homepage. Poll waits on PPCA.',
  },
  {
    platform: 'facebook_page',
    handle: 'familydaycareservices',
    displayName: 'Family Day Care Services',
    city: 'Toronto',
    region: 'toronto',
    category: 'T1',
    fsa: null,
    sourceUrl: 'https://www.familydaycare.com/',
    active: true,
    note: 'Homepage linked this Facebook page and no Instagram handle. Page names Toronto. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'earlyonsec',
    displayName: 'EarlyOn SEC',
    city: 'Woodbridge',
    region: 'york',
    category: 'T1',
    fsa: null,
    sourceUrl: 'https://www.earlyonsec.com/',
    active: false,
    note: 'Handle is on the homepage. About page lists Woodbridge, an Aurora-area postal code, and Caledon, so no single region. Left inactive.',
  },
  {
    platform: 'facebook_page',
    handle: 'earlyonsec',
    displayName: 'EarlyOn SEC',
    city: 'Woodbridge',
    region: 'york',
    category: 'T1',
    fsa: null,
    sourceUrl: 'https://www.earlyonsec.com/',
    active: false,
    note: 'Same multi-area about page. Left inactive. Poll would wait on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'eastendchildrenscentre',
    displayName: "East End Children's Centre",
    city: 'Toronto',
    region: 'toronto',
    category: 'T1',
    fsa: null,
    sourceUrl: 'https://www.eastendchildrenscentre.org/',
    active: false,
    note: 'Handle is on the homepage. Fetched text did not name a city. Left inactive.',
  },
  {
    platform: 'facebook_page',
    handle: 'kimbournedropin',
    displayName: 'Kimbourne Drop-in',
    city: 'Toronto',
    region: 'toronto',
    category: 'T1',
    fsa: null,
    sourceUrl: 'https://www.eastendchildrenscentre.org/',
    active: false,
    note: 'Facebook page on that homepage. City not in the fetched text. Left inactive.',
  },
  {
    platform: 'instagram',
    handle: 'downeysfarm',
    displayName: "Downey's Farm",
    city: 'Caledon',
    region: 'peel',
    category: 'T2',
    fsa: 'L7C',
    sourceUrl: 'https://downeysfarm.com/',
    active: true,
    note: 'Homepage linked DowneysFarm. Contact page lists Caledon L7C. Stored lowercase.',
  },
  {
    platform: 'facebook_page',
    handle: 'downeysfarm',
    displayName: "Downey's Farm",
    city: 'Caledon',
    region: 'peel',
    category: 'T2',
    fsa: 'L7C',
    sourceUrl: 'https://downeysfarm.com/',
    active: true,
    note: 'Facebook page on the homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'chudleighsfarm',
    displayName: "Chudleigh's Farm",
    city: 'Milton',
    region: 'halton',
    category: 'T2',
    fsa: 'L9T',
    sourceUrl: 'https://www.chudleighs.com/',
    active: true,
    note: 'Homepage linked this handle. Visit page lists Milton L9T.',
  },
  {
    platform: 'facebook_page',
    handle: 'chudleighs',
    displayName: "Chudleigh's",
    city: 'Milton',
    region: 'halton',
    category: 'T2',
    fsa: 'L9T',
    sourceUrl: 'https://www.chudleighs.com/',
    active: true,
    note: 'Facebook page on the homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'chudleighsdesserts',
    displayName: "Chudleigh's Desserts",
    city: 'Milton',
    region: 'halton',
    category: 'T14',
    fsa: 'L9T',
    sourceUrl: 'https://www.chudleighs.com/',
    active: true,
    note: 'Second handle on the same homepage. Bakery counter, not the orchard program.',
  },
  {
    platform: 'instagram',
    handle: 'springridgefarm',
    displayName: 'Springridge Farm',
    city: 'Milton',
    region: 'halton',
    category: 'T2',
    fsa: 'L9E',
    sourceUrl: 'https://www.springridgefarm.com/',
    active: true,
    note: 'Homepage linked this handle and names Milton L9E.',
  },
  {
    platform: 'instagram',
    handle: 'dixie_orchards',
    displayName: 'Dixie Orchards',
    city: 'Mississauga',
    region: 'peel',
    category: 'T2',
    fsa: null,
    sourceUrl: 'https://dixieorchards.com/',
    active: true,
    note: 'Homepage linked this handle.',
  },
  {
    platform: 'facebook_page',
    handle: 'dixieorchards',
    displayName: 'Dixie Orchards',
    city: 'Mississauga',
    region: 'peel',
    category: 'T2',
    fsa: null,
    sourceUrl: 'https://dixieorchards.com/',
    active: true,
    note: 'Facebook page on the homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'forsythefamilyfarms',
    displayName: 'Forsythe Family Farms',
    city: 'Greenbank',
    region: 'durham',
    category: 'T2',
    fsa: null,
    sourceUrl: 'https://www.forsythefamilyfarms.com/',
    active: true,
    note: 'Homepage linked this handle and names Greenbank. Toronto is also mentioned on the page.',
  },
  {
    platform: 'facebook_page',
    handle: 'forsythefamilyfarms',
    displayName: 'Forsythe Family Farms',
    city: 'Greenbank',
    region: 'durham',
    category: 'T2',
    fsa: null,
    sourceUrl: 'https://www.forsythefamilyfarms.com/',
    active: true,
    note: 'Facebook page on the homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'watsonfarms',
    displayName: 'Watson Farms',
    city: 'Bowmanville',
    region: 'durham',
    category: 'T2',
    fsa: 'L1C',
    sourceUrl: 'https://watsonfarms.ca/',
    active: true,
    note: 'Homepage linked this handle and names Bowmanville L1C.',
  },
  {
    platform: 'instagram',
    handle: 'torontolibrary',
    displayName: 'Toronto Public Library',
    city: 'Toronto',
    region: 'toronto',
    category: 'T3',
    fsa: null,
    sourceUrl: 'https://www.torontopubliclibrary.ca/',
    active: true,
    note: 'Library homepage linked this handle, 2026-09-27.',
  },
  {
    platform: 'facebook_page',
    handle: 'torontopubliclibrary',
    displayName: 'Toronto Public Library',
    city: 'Toronto',
    region: 'toronto',
    category: 'T3',
    fsa: null,
    sourceUrl: 'https://www.torontopubliclibrary.ca/',
    active: true,
    note: 'Facebook page on the library homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'mississaugalib',
    displayName: 'Mississauga Library',
    city: 'Mississauga',
    region: 'peel',
    category: 'T3',
    fsa: null,
    sourceUrl: 'https://www.mississauga.ca/library/',
    active: true,
    note: 'Library homepage linked this handle, 2026-09-27.',
  },
  {
    platform: 'facebook_page',
    handle: 'mississaugalibrary',
    displayName: 'Mississauga Library',
    city: 'Mississauga',
    region: 'peel',
    category: 'T3',
    fsa: null,
    sourceUrl: 'https://www.mississauga.ca/library/',
    active: true,
    note: 'Facebook page on the library homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'bramptonlibrary',
    displayName: 'Brampton Library',
    city: 'Brampton',
    region: 'peel',
    category: 'T3',
    fsa: null,
    sourceUrl: 'https://www.bramptonlibrary.ca/',
    active: true,
    note: 'Library homepage linked this handle, 2026-09-27.',
  },
  {
    platform: 'instagram',
    handle: 'vaughanpubliclibraries',
    displayName: 'Vaughan Public Libraries',
    city: 'Vaughan',
    region: 'york',
    category: 'T3',
    fsa: null,
    sourceUrl: 'https://www.vaughanpl.info/',
    active: true,
    note: 'Library homepage linked this handle, 2026-09-27.',
  },
  {
    platform: 'facebook_page',
    handle: 'vaughanpl',
    displayName: 'Vaughan Public Libraries',
    city: 'Vaughan',
    region: 'york',
    category: 'T3',
    fsa: null,
    sourceUrl: 'https://www.vaughanpl.info/',
    active: true,
    note: 'Facebook page on the library homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'richmondhillpl',
    displayName: 'Richmond Hill Public Library',
    city: 'Richmond Hill',
    region: 'york',
    category: 'T3',
    fsa: null,
    sourceUrl: 'https://www.rhpl.ca/',
    active: true,
    note: 'Library homepage linked this handle, 2026-09-27.',
  },
  {
    platform: 'facebook_page',
    handle: 'richmondhillpl',
    displayName: 'Richmond Hill Public Library',
    city: 'Richmond Hill',
    region: 'york',
    category: 'T3',
    fsa: null,
    sourceUrl: 'https://www.rhpl.ca/',
    active: true,
    note: 'Facebook page on the library homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'newmarketlibrary',
    displayName: 'Newmarket Public Library',
    city: 'Newmarket',
    region: 'york',
    category: 'T3',
    fsa: null,
    sourceUrl: 'https://www.newmarketpl.ca/',
    active: true,
    note: 'Library homepage linked this handle, 2026-09-27.',
  },
  {
    platform: 'instagram',
    handle: 'king_township_public_library',
    displayName: 'King Township Public Library',
    city: 'King City',
    region: 'york',
    category: 'T3',
    fsa: null,
    sourceUrl: 'https://www.kinglibrary.ca/',
    active: true,
    note: 'Library homepage linked this handle, 2026-09-27.',
  },
  {
    platform: 'facebook_page',
    handle: 'ktplibrary',
    displayName: 'King Township Public Library',
    city: 'King City',
    region: 'york',
    category: 'T3',
    fsa: null,
    sourceUrl: 'https://www.kinglibrary.ca/',
    active: true,
    note: 'Facebook page on the library homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'georginalibrary',
    displayName: 'Georgina Public Library',
    city: 'Georgina',
    region: 'york',
    category: 'T3',
    fsa: null,
    sourceUrl: 'https://www.georginalibrary.ca/',
    active: true,
    note: 'Library homepage linked this handle, 2026-09-27.',
  },
  {
    platform: 'facebook_page',
    handle: 'georginapl',
    displayName: 'Georgina Public Library',
    city: 'Georgina',
    region: 'york',
    category: 'T3',
    fsa: null,
    sourceUrl: 'https://www.georginalibrary.ca/',
    active: true,
    note: 'Facebook page on the library homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'ajaxpubliclibrary',
    displayName: 'Ajax Public Library',
    city: 'Ajax',
    region: 'durham',
    category: 'T3',
    fsa: null,
    sourceUrl: 'https://www.ajaxlibrary.ca/',
    active: true,
    note: 'Library homepage linked this handle, 2026-09-27.',
  },
  {
    platform: 'facebook_page',
    handle: 'ajaxpubliclibrary',
    displayName: 'Ajax Public Library',
    city: 'Ajax',
    region: 'durham',
    category: 'T3',
    fsa: null,
    sourceUrl: 'https://www.ajaxlibrary.ca/',
    active: true,
    note: 'Facebook page on the library homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'whitbylibrary',
    displayName: 'Whitby Public Library',
    city: 'Whitby',
    region: 'durham',
    category: 'T3',
    fsa: null,
    sourceUrl: 'https://www.whitbylibrary.ca/',
    active: true,
    note: 'Library homepage linked this handle, 2026-09-27.',
  },
  {
    platform: 'facebook_page',
    handle: 'whitbylibrary',
    displayName: 'Whitby Public Library',
    city: 'Whitby',
    region: 'durham',
    category: 'T3',
    fsa: null,
    sourceUrl: 'https://www.whitbylibrary.ca/',
    active: true,
    note: 'Facebook page on the library homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'claringtonlma',
    displayName: 'Clarington Library Museums and Archives',
    city: 'Bowmanville',
    region: 'durham',
    category: 'T3',
    fsa: null,
    sourceUrl: 'https://www.clarington-library.on.ca/',
    active: true,
    note: 'Library homepage linked this handle, 2026-09-27.',
  },
  {
    platform: 'facebook_page',
    handle: 'claringtonlma',
    displayName: 'Clarington Library Museums and Archives',
    city: 'Bowmanville',
    region: 'durham',
    category: 'T3',
    fsa: null,
    sourceUrl: 'https://www.clarington-library.on.ca/',
    active: true,
    note: 'Facebook page on the library homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'oakvillelibrary',
    displayName: 'Oakville Public Library',
    city: 'Oakville',
    region: 'halton',
    category: 'T3',
    fsa: null,
    sourceUrl: 'https://www.opl.ca/',
    active: true,
    note: 'Library homepage linked this handle, 2026-09-27.',
  },
  {
    platform: 'instagram',
    handle: 'burlonlibrary',
    displayName: 'Burlington Public Library',
    city: 'Burlington',
    region: 'halton',
    category: 'T3',
    fsa: null,
    sourceUrl: 'https://www.bpl.on.ca/',
    active: true,
    note: 'Library homepage linked this handle, 2026-09-27.',
  },
  {
    platform: 'facebook_page',
    handle: 'burlonlibrary',
    displayName: 'Burlington Public Library',
    city: 'Burlington',
    region: 'halton',
    category: 'T3',
    fsa: null,
    sourceUrl: 'https://www.bpl.on.ca/',
    active: true,
    note: 'Facebook page on the library homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'romtoronto',
    displayName: 'Royal Ontario Museum',
    city: 'Toronto',
    region: 'toronto',
    category: 'T4',
    fsa: null,
    sourceUrl: 'https://www.rom.on.ca/',
    active: true,
    note: 'Homepage linked this handle, 2026-09-27.',
  },
  {
    platform: 'facebook_page',
    handle: 'royalontariomuseum',
    displayName: 'Royal Ontario Museum',
    city: 'Toronto',
    region: 'toronto',
    category: 'T4',
    fsa: null,
    sourceUrl: 'https://www.rom.on.ca/',
    active: true,
    note: 'Facebook page on the same homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'ontariosciencecentre',
    displayName: 'Ontario Science Centre',
    city: 'Toronto',
    region: 'toronto',
    category: 'T4',
    fsa: null,
    sourceUrl: 'https://www.ontariosciencecentre.ca/',
    active: true,
    note: 'Homepage linked this handle, 2026-09-27.',
  },
  {
    platform: 'facebook_page',
    handle: 'ontariosciencecentre',
    displayName: 'Ontario Science Centre',
    city: 'Toronto',
    region: 'toronto',
    category: 'T4',
    fsa: null,
    sourceUrl: 'https://www.ontariosciencecentre.ca/',
    active: true,
    note: 'Facebook page on the same homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'thetorontozoo',
    displayName: 'Toronto Zoo',
    city: 'Toronto',
    region: 'toronto',
    category: 'T4',
    fsa: null,
    sourceUrl: 'https://www.torontozoo.com/',
    active: true,
    note: 'Homepage linked this handle, 2026-09-27.',
  },
  {
    platform: 'facebook_page',
    handle: 'thetorontozoo',
    displayName: 'Toronto Zoo',
    city: 'Toronto',
    region: 'toronto',
    category: 'T4',
    fsa: null,
    sourceUrl: 'https://www.torontozoo.com/',
    active: true,
    note: 'Facebook page on the same homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'ripleysaquaca',
    displayName: "Ripley's Aquarium of Canada",
    city: 'Toronto',
    region: 'toronto',
    category: 'T4',
    fsa: null,
    sourceUrl: 'https://www.ripleyaquariums.com/canada/',
    active: true,
    note: 'Homepage linked this handle, 2026-09-27.',
  },
  {
    platform: 'facebook_page',
    handle: 'ripleysaquariumcanada',
    displayName: "Ripley's Aquarium of Canada",
    city: 'Toronto',
    region: 'toronto',
    category: 'T4',
    fsa: null,
    sourceUrl: 'https://www.ripleyaquariums.com/canada/',
    active: true,
    note: 'Facebook page on the same homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'tbg_canada',
    displayName: 'Toronto Botanical Garden',
    city: 'Toronto',
    region: 'toronto',
    category: 'T4',
    fsa: null,
    sourceUrl: 'https://www.torontobotanicalgarden.ca/',
    active: true,
    note: 'Homepage linked this handle, 2026-09-27.',
  },
  {
    platform: 'facebook_page',
    handle: 'torontobotanicalgarden',
    displayName: 'Toronto Botanical Garden',
    city: 'Toronto',
    region: 'toronto',
    category: 'T4',
    fsa: null,
    sourceUrl: 'https://www.torontobotanicalgarden.ca/',
    active: true,
    note: 'Facebook page on the same homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'evergreencanada',
    displayName: 'Evergreen',
    city: 'Toronto',
    region: 'toronto',
    category: 'T4',
    fsa: null,
    sourceUrl: 'https://www.evergreen.ca/',
    active: true,
    note: 'Homepage linked this handle, 2026-09-27.',
  },
  {
    platform: 'facebook_page',
    handle: 'evergreencanada',
    displayName: 'Evergreen',
    city: 'Toronto',
    region: 'toronto',
    category: 'T4',
    fsa: null,
    sourceUrl: 'https://www.evergreen.ca/',
    active: true,
    note: 'Facebook page on the same homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'fortyorkfoundation',
    displayName: 'Fort York Foundation',
    city: 'Toronto',
    region: 'toronto',
    category: 'T4',
    fsa: null,
    sourceUrl: 'https://www.fortyork.ca/',
    active: true,
    note: 'Homepage linked this handle, 2026-09-27.',
  },
  {
    platform: 'instagram',
    handle: 'tohistorymuseums',
    displayName: 'Toronto History Museums',
    city: 'Toronto',
    region: 'toronto',
    category: 'T4',
    fsa: null,
    sourceUrl: 'https://www.fortyork.ca/',
    active: true,
    note: 'Homepage linked this handle, 2026-09-27.',
  },
  {
    platform: 'facebook_page',
    handle: 'tohistorymuseums',
    displayName: 'Toronto History Museums',
    city: 'Toronto',
    region: 'toronto',
    category: 'T4',
    fsa: null,
    sourceUrl: 'https://www.fortyork.ca/',
    active: true,
    note: 'Facebook page on the same homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'textilemuseumofcanada',
    displayName: 'Textile Museum of Canada',
    city: 'Toronto',
    region: 'toronto',
    category: 'T4',
    fsa: null,
    sourceUrl: 'https://textilemuseum.ca/',
    active: true,
    note: 'Homepage linked this handle, 2026-09-27.',
  },
  {
    platform: 'facebook_page',
    handle: 'textilemuseumofcanada',
    displayName: 'Textile Museum of Canada',
    city: 'Toronto',
    region: 'toronto',
    category: 'T4',
    fsa: null,
    sourceUrl: 'https://textilemuseum.ca/',
    active: true,
    note: 'Facebook page on the same homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'agakhanmuseum',
    displayName: 'Aga Khan Museum',
    city: 'Toronto',
    region: 'toronto',
    category: 'T4',
    fsa: null,
    sourceUrl: 'https://www.agakhanmuseum.org/',
    active: true,
    note: 'Homepage linked this handle, 2026-09-27.',
  },
  {
    platform: 'facebook_page',
    handle: 'agakhanmuseumtoronto',
    displayName: 'Aga Khan Museum',
    city: 'Toronto',
    region: 'toronto',
    category: 'T4',
    fsa: null,
    sourceUrl: 'https://www.agakhanmuseum.org/',
    active: true,
    note: 'Facebook page on the same homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'casalomatoronto',
    displayName: 'Casa Loma',
    city: 'Toronto',
    region: 'toronto',
    category: 'T4',
    fsa: null,
    sourceUrl: 'https://casaloma.ca/',
    active: true,
    note: 'Homepage linked this handle, 2026-09-27.',
  },
  {
    platform: 'facebook_page',
    handle: 'casalomacastle',
    displayName: 'Casa Loma',
    city: 'Toronto',
    region: 'toronto',
    category: 'T4',
    fsa: null,
    sourceUrl: 'https://casaloma.ca/',
    active: true,
    note: 'Facebook page on the same homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'centrevillefun',
    displayName: 'Centreville Amusement Park',
    city: 'Toronto',
    region: 'toronto',
    category: 'T4',
    fsa: null,
    sourceUrl: 'https://www.centreisland.ca/',
    active: true,
    note: 'Homepage linked this handle, 2026-09-27.',
  },
  {
    platform: 'facebook_page',
    handle: 'centrevilleamusementpark',
    displayName: 'Centreville Amusement Park',
    city: 'Toronto',
    region: 'toronto',
    category: 'T4',
    fsa: null,
    sourceUrl: 'https://www.centreisland.ca/',
    active: true,
    note: 'Facebook page on the same homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'canadaswonderland',
    displayName: "Canada's Wonderland",
    city: 'Vaughan',
    region: 'york',
    category: 'T4',
    fsa: null,
    sourceUrl: 'https://www.canadaswonderland.com/',
    active: true,
    note: 'Homepage linked this handle and names Vaughan.',
  },
  {
    platform: 'facebook_page',
    handle: 'canadaswonderland',
    displayName: "Canada's Wonderland",
    city: 'Vaughan',
    region: 'york',
    category: 'T4',
    fsa: null,
    sourceUrl: 'https://www.canadaswonderland.com/',
    active: true,
    note: 'Facebook page on the same homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'africanlionsafari',
    displayName: 'African Lion Safari',
    city: 'Cambridge',
    region: 'day_trip',
    category: 'T4',
    fsa: null,
    sourceUrl: 'https://lionsafari.com/',
    active: true,
    note: 'Homepage linked this handle and names Cambridge. Outside the five regions, so this is a day trip.',
  },
  {
    platform: 'facebook_page',
    handle: 'africanlionsafaricanada',
    displayName: 'African Lion Safari',
    city: 'Cambridge',
    region: 'day_trip',
    category: 'T4',
    fsa: null,
    sourceUrl: 'https://lionsafari.com/',
    active: true,
    note: 'Facebook page on the same homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'ontarioplace',
    displayName: 'Ontario Place',
    city: 'Toronto',
    region: 'toronto',
    category: 'T4',
    fsa: null,
    sourceUrl: 'https://www.ontarioplace.com/',
    active: true,
    note: 'Homepage linked this handle, 2026-09-27.',
  },
  {
    platform: 'facebook_page',
    handle: 'ontarioplace',
    displayName: 'Ontario Place',
    city: 'Toronto',
    region: 'toronto',
    category: 'T4',
    fsa: null,
    sourceUrl: 'https://www.ontarioplace.com/',
    active: true,
    note: 'Facebook page on the same homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'ksg_m',
    displayName: 'Kids SuperGym Mississauga',
    city: 'Mississauga',
    region: 'peel',
    category: 'T5',
    fsa: 'L5L',
    sourceUrl: 'https://kids-supergym.com/',
    active: true,
    note: 'Homepage linked this handle and names Mississauga L5L.',
  },
  {
    platform: 'facebook_page',
    handle: 'kidssupergymmississauga',
    displayName: 'Kids SuperGym Mississauga',
    city: 'Mississauga',
    region: 'peel',
    category: 'T5',
    fsa: 'L5L',
    sourceUrl: 'https://kids-supergym.com/',
    active: true,
    note: 'Facebook page on the homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'theschoolcreativearts',
    displayName: 'The School of Creative Arts',
    city: 'Mississauga',
    region: 'peel',
    category: 'T6',
    fsa: 'L5G',
    sourceUrl: 'https://www.theschoolcreativearts.com/',
    active: true,
    note: 'Homepage linked this handle and names Mississauga L5G.',
  },
  {
    platform: 'facebook_page',
    handle: 'theschoolcreativearts',
    displayName: 'The School of Creative Arts',
    city: 'Mississauga',
    region: 'peel',
    category: 'T6',
    fsa: 'L5G',
    sourceUrl: 'https://www.theschoolcreativearts.com/',
    active: true,
    note: 'Facebook page on the homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'jorgendance',
    displayName: "Canada's Ballet Jorgen",
    city: 'Toronto',
    region: 'toronto',
    category: 'T6',
    fsa: null,
    sourceUrl: 'https://canadasballetjorgen.ca/',
    active: true,
    note: 'Homepage linked this handle.',
  },
  {
    platform: 'facebook_page',
    handle: 'jorgendance',
    displayName: "Canada's Ballet Jorgen",
    city: 'Toronto',
    region: 'toronto',
    category: 'T6',
    fsa: null,
    sourceUrl: 'https://canadasballetjorgen.ca/',
    active: true,
    note: 'Facebook page on the homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'torontosymphony',
    displayName: 'Toronto Symphony Orchestra',
    city: 'Toronto',
    region: 'toronto',
    category: 'T6',
    fsa: null,
    sourceUrl: 'https://www.tso.ca/',
    active: true,
    note: 'Homepage linked this handle.',
  },
  {
    platform: 'facebook_page',
    handle: 'torontosymphonyorchestra',
    displayName: 'Toronto Symphony Orchestra',
    city: 'Toronto',
    region: 'toronto',
    category: 'T6',
    fsa: null,
    sourceUrl: 'https://www.tso.ca/',
    active: true,
    note: 'Facebook page on the homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'ypttoronto',
    displayName: "Young People's Theatre",
    city: 'Toronto',
    region: 'toronto',
    category: 'T6',
    fsa: null,
    sourceUrl: 'https://www.youngpeoplestheatre.org/',
    active: true,
    note: 'Homepage linked this handle.',
  },
  {
    platform: 'facebook_page',
    handle: 'youngpeoplestheatre',
    displayName: "Young People's Theatre",
    city: 'Toronto',
    region: 'toronto',
    category: 'T6',
    fsa: null,
    sourceUrl: 'https://www.youngpeoplestheatre.org/',
    active: true,
    note: 'Facebook page on the homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'rosspettypro',
    displayName: 'Ross Petty Productions',
    city: 'Toronto',
    region: 'toronto',
    category: 'T6',
    fsa: null,
    sourceUrl: 'https://www.rosspetty.com/',
    active: true,
    note: 'Homepage linked this handle. Family pantomime.',
  },
  {
    platform: 'facebook_page',
    handle: 'rosspettyproductions',
    displayName: 'Ross Petty Productions',
    city: 'Toronto',
    region: 'toronto',
    category: 'T6',
    fsa: null,
    sourceUrl: 'https://www.rosspetty.com/',
    active: true,
    note: 'Facebook page on the homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'trca_hq',
    displayName: 'Toronto and Region Conservation Authority',
    city: 'Toronto',
    region: 'toronto',
    category: 'T9',
    fsa: null,
    sourceUrl: 'https://trca.ca/',
    active: true,
    note: 'Homepage linked this handle. Page names a Toronto address and watershed sites in the GTA. Primary region is the Toronto HQ.',
  },
  {
    platform: 'facebook_page',
    handle: 'torontoconservation',
    displayName: 'Toronto and Region Conservation Authority',
    city: 'Toronto',
    region: 'toronto',
    category: 'T9',
    fsa: null,
    sourceUrl: 'https://trca.ca/',
    active: true,
    note: 'Facebook page on the homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'conservationhalton',
    displayName: 'Conservation Halton',
    city: 'Burlington',
    region: 'halton',
    category: 'T9',
    fsa: 'L7P',
    sourceUrl: 'https://www.conservationhalton.ca/',
    active: true,
    note: 'Homepage linked this handle and names Burlington L7P.',
  },
  {
    platform: 'facebook_page',
    handle: 'conservationhalton',
    displayName: 'Conservation Halton',
    city: 'Burlington',
    region: 'halton',
    category: 'T9',
    fsa: 'L7P',
    sourceUrl: 'https://www.conservationhalton.ca/',
    active: true,
    note: 'Facebook page on the homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'ralphthorntoncommunitycentre',
    displayName: 'Ralph Thornton Community Centre',
    city: 'Toronto',
    region: 'toronto',
    category: 'T9',
    fsa: null,
    sourceUrl: 'https://www.ralphthornton.org/',
    active: true,
    note: 'Homepage linked this handle. Page names Toronto.',
  },
  {
    platform: 'facebook_page',
    handle: 'ralphthorntoncommunitycentre',
    displayName: 'Ralph Thornton Community Centre',
    city: 'Toronto',
    region: 'toronto',
    category: 'T9',
    fsa: null,
    sourceUrl: 'https://www.ralphthornton.org/',
    active: true,
    note: 'Facebook page on the homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'jumbalooplaygrounds',
    displayName: 'Jumbaloo Playgrounds',
    city: 'Mississauga',
    region: 'peel',
    category: 'T10',
    fsa: null,
    sourceUrl: 'https://jumbaloo.com/',
    active: true,
    note: 'Homepage linked this handle and names Mississauga and Oakville. Primary region is Peel.',
  },
  {
    platform: 'facebook_page',
    handle: 'jumbalooplaygrounds',
    displayName: 'Jumbaloo Playgrounds',
    city: 'Mississauga',
    region: 'peel',
    category: 'T10',
    fsa: null,
    sourceUrl: 'https://jumbaloo.com/',
    active: true,
    note: 'Facebook page on the homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'kidsapiamississauga',
    displayName: 'Kids Apia Mississauga',
    city: 'Mississauga',
    region: 'peel',
    category: 'T10',
    fsa: 'L5M',
    sourceUrl: 'https://kidsapia.com/',
    active: true,
    note: 'Homepage linked this handle and names Mississauga L5M.',
  },
  {
    platform: 'instagram',
    handle: 'playloola',
    displayName: 'Play Loola',
    city: 'Oshawa',
    region: 'durham',
    category: 'T10',
    fsa: 'L1J',
    sourceUrl: 'https://playloola.com/',
    active: true,
    note: 'Homepage linked this handle and names Oshawa L1J, plus Whitby and Bowmanville.',
  },
  {
    platform: 'facebook_page',
    handle: 'playloola',
    displayName: 'Play Loola',
    city: 'Oshawa',
    region: 'durham',
    category: 'T10',
    fsa: 'L1J',
    sourceUrl: 'https://playloola.com/',
    active: true,
    note: 'Facebook page on the homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'playdiumca',
    displayName: 'Playdium Vaughan',
    city: 'Vaughan',
    region: 'york',
    category: 'T10',
    fsa: null,
    sourceUrl: 'https://www.playdium.com/',
    active: true,
    note: 'Homepage links this handle and headlines Playdium Vaughan now open.',
  },
  {
    platform: 'instagram',
    handle: 'ymcagta',
    displayName: 'YMCA of Greater Toronto',
    city: 'Toronto',
    region: 'toronto',
    category: 'T11',
    fsa: null,
    sourceUrl: 'https://www.ymcagta.org/',
    active: true,
    note: 'Homepage linked this handle. Page lists Toronto first and centres in the GTA. Primary region is the Toronto HQ.',
  },
  {
    platform: 'facebook_page',
    handle: 'ymcagta',
    displayName: 'YMCA of Greater Toronto',
    city: 'Toronto',
    region: 'toronto',
    category: 'T11',
    fsa: null,
    sourceUrl: 'https://www.ymcagta.org/',
    active: true,
    note: 'Facebook page on the homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'bgcpeel',
    displayName: 'BGC Peel',
    city: 'Brampton',
    region: 'peel',
    category: 'T11',
    fsa: null,
    sourceUrl: 'https://www.bgcpeel.org/',
    active: true,
    note: 'Homepage linked this handle and names Brampton.',
  },
  {
    platform: 'facebook_page',
    handle: 'bgcpeelclub',
    displayName: 'BGC Peel',
    city: 'Brampton',
    region: 'peel',
    category: 'T11',
    fsa: null,
    sourceUrl: 'https://www.bgcpeel.org/',
    active: true,
    note: 'Facebook page on the homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'plasp_ccs',
    displayName: 'PLASP Child Care Services',
    city: 'Brampton',
    region: 'peel',
    category: 'T11',
    fsa: null,
    sourceUrl: 'https://www.plasp.com/',
    active: true,
    note: 'Homepage linked this handle. Page names Toronto and Brampton. Primary region is Peel.',
  },
  {
    platform: 'facebook_page',
    handle: 'plaspchildcareservices',
    displayName: 'PLASP Child Care Services',
    city: 'Brampton',
    region: 'peel',
    category: 'T11',
    fsa: null,
    sourceUrl: 'https://www.plasp.com/',
    active: true,
    note: 'Facebook page on the homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'yorktownfamilyservices',
    displayName: 'Yorktown Family Services',
    city: 'Toronto',
    region: 'toronto',
    category: 'T13',
    fsa: null,
    sourceUrl: 'https://yorktownfamilyservices.com/',
    active: true,
    note: 'Homepage linked this handle and names Toronto.',
  },
  {
    platform: 'facebook_page',
    handle: 'yorktownfamilyservices',
    displayName: 'Yorktown Family Services',
    city: 'Toronto',
    region: 'toronto',
    category: 'T13',
    fsa: null,
    sourceUrl: 'https://yorktownfamilyservices.com/',
    active: true,
    note: 'Facebook page on the homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'tngcommunityto',
    displayName: 'The Neighbourhood Group',
    city: 'Toronto',
    region: 'toronto',
    category: 'T13',
    fsa: null,
    sourceUrl: 'https://www.tngcommunityto.org/',
    active: true,
    note: 'Homepage linked this handle and names Toronto.',
  },
  {
    platform: 'facebook_page',
    handle: 'tngcommunityto',
    displayName: 'The Neighbourhood Group',
    city: 'Toronto',
    region: 'toronto',
    category: 'T13',
    fsa: null,
    sourceUrl: 'https://www.tngcommunityto.org/',
    active: true,
    note: 'Facebook page on the homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'grandviewkids',
    displayName: 'Grandview Kids',
    city: 'Ajax',
    region: 'durham',
    category: 'T13',
    fsa: null,
    sourceUrl: 'https://www.grandviewkids.ca/',
    active: true,
    note: 'Homepage linked this handle. Contact page lists Ajax, Bowmanville, Oshawa, and Whitby.',
  },
  {
    platform: 'facebook_page',
    handle: 'grandviewkids',
    displayName: 'Grandview Kids',
    city: 'Ajax',
    region: 'durham',
    category: 'T13',
    fsa: null,
    sourceUrl: 'https://www.grandviewkids.ca/',
    active: true,
    note: 'Facebook page on the homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'erinoakkids',
    displayName: 'ErinoakKids',
    city: 'Brampton',
    region: 'peel',
    category: 'T13',
    fsa: null,
    sourceUrl: 'https://www.erinoakkids.ca/',
    active: true,
    note: 'Homepage linked this handle. Contact page lists Brampton, Mississauga, and Oakville. Primary region is Peel.',
  },
  {
    platform: 'facebook_page',
    handle: 'erinoakkids',
    displayName: 'ErinoakKids',
    city: 'Brampton',
    region: 'peel',
    category: 'T13',
    fsa: null,
    sourceUrl: 'https://www.erinoakkids.ca/',
    active: true,
    note: 'Facebook page on the homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'kinarkcfs',
    displayName: 'Kinark Child and Family Services',
    city: 'York Region',
    region: 'york',
    category: 'T13',
    fsa: null,
    sourceUrl: 'https://www.kinark.on.ca/',
    active: false,
    note: 'Handle is on the homepage. Fetched text did not name a city. Left inactive.',
  },
  {
    platform: 'facebook_page',
    handle: 'kinark',
    displayName: 'Kinark Child and Family Services',
    city: 'York Region',
    region: 'york',
    category: 'T13',
    fsa: null,
    sourceUrl: 'https://www.kinark.on.ca/',
    active: false,
    note: 'Facebook page on the homepage. City not in the fetched text. Left inactive.',
  },
  {
    platform: 'instagram',
    handle: 'cntower',
    displayName: 'CN Tower',
    city: 'Toronto',
    region: 'toronto',
    category: 'T14',
    fsa: null,
    sourceUrl: 'https://www.cntower.ca/',
    active: true,
    note: 'Homepage linked this handle and names Toronto.',
  },
  {
    platform: 'instagram',
    handle: 'tourcntower360',
    displayName: 'CN Tower EdgeWalk',
    city: 'Toronto',
    region: 'toronto',
    category: 'T14',
    fsa: null,
    sourceUrl: 'https://www.cntower.ca/',
    active: true,
    note: 'Second handle on the CN Tower homepage.',
  },
  {
    platform: 'facebook_page',
    handle: 'cntower',
    displayName: 'CN Tower',
    city: 'Toronto',
    region: 'toronto',
    category: 'T14',
    fsa: null,
    sourceUrl: 'https://www.cntower.ca/',
    active: true,
    note: 'Facebook page on the homepage. Poll waits on PPCA.',
  },
  {
    platform: 'facebook_page',
    handle: 'cntower360',
    displayName: 'CN Tower EdgeWalk',
    city: 'Toronto',
    region: 'toronto',
    category: 'T14',
    fsa: null,
    sourceUrl: 'https://www.cntower.ca/',
    active: true,
    note: 'Second Facebook page on the CN Tower homepage. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'ldcnorthamerica',
    displayName: 'LEGOLAND Discovery Centre',
    city: 'Vaughan',
    region: 'york',
    category: 'T14',
    fsa: null,
    sourceUrl: 'https://www.legolanddiscoverycentre.com/toronto/',
    active: true,
    note: "Toronto marketing page linked this handle. The centre sits at Canada's Wonderland in Vaughan, so the region is York.",
  },
  {
    platform: 'facebook_page',
    handle: 'ldctoronto',
    displayName: 'LEGOLAND Discovery Centre Toronto',
    city: 'Vaughan',
    region: 'york',
    category: 'T14',
    fsa: null,
    sourceUrl: 'https://www.legolanddiscoverycentre.com/toronto/',
    active: true,
    note: 'Facebook page on the same marketing page. Venue is Vaughan. Poll waits on PPCA.',
  },
  {
    platform: 'facebook_page',
    handle: 'riverdalefarmtoronto',
    displayName: 'Riverdale Farm',
    city: 'Toronto',
    region: 'toronto',
    category: 'T4',
    fsa: null,
    sourceUrl: 'https://www.riverdalefarmtoronto.ca/',
    active: true,
    note: 'Homepage linked this Facebook page and no Instagram handle. Poll waits on PPCA.',
  },
  {
    platform: 'instagram',
    handle: 'blogto',
    displayName: 'BlogTO',
    city: 'Toronto',
    region: 'toronto',
    category: 'T9',
    fsa: null,
    sourceUrl: 'https://www.blogto.com/',
    active: true,
    note: 'Homepage linked this handle. City events desk. Structured rec catalogs stay on the civic rails.',
  },
  {
    platform: 'instagram',
    handle: 'rocketbeartoronto',
    displayName: 'Rocket Bear Play',
    city: 'Toronto',
    region: 'toronto',
    category: 'T10',
    fsa: null,
    sourceUrl: 'https://mykidspass.online/kids-activity-directory/',
    active: true,
    note: 'Kids Pass directory card linked this handle on 2026-09-27. Card title Rocket Bear Play; handle names Toronto.',
  },
  {
    platform: 'instagram',
    handle: 'happyplanet.kidsscarborough',
    displayName: 'Happy Planet Kids',
    city: 'Scarborough',
    region: 'toronto',
    category: 'T10',
    fsa: null,
    sourceUrl: 'https://mykidspass.online/kids-activity-directory/',
    active: true,
    note: 'Kids Pass directory card linked this handle on 2026-09-27. Handle names Scarborough.',
  },
  {
    platform: 'instagram',
    handle: 'kidsvilletoronto',
    displayName: 'Kidsville Toronto',
    city: 'Toronto',
    region: 'toronto',
    category: 'T10',
    fsa: null,
    sourceUrl: 'https://mykidspass.online/kids-activity-directory/',
    active: true,
    note: 'Kids Pass directory card linked this handle on 2026-09-27. Card title Kidsville Toronto.',
  },
  {
    platform: 'instagram',
    handle: 'jumpforjoyonthedanforth',
    displayName: 'Jump For Joy Play Centre',
    city: 'Toronto',
    region: 'toronto',
    category: 'T10',
    fsa: null,
    sourceUrl: 'https://mykidspass.online/kids-activity-directory/',
    active: true,
    note: 'Kids Pass directory card linked this handle on 2026-09-27. Danforth is in the handle. Also posts PA-day camps.',
  },
  {
    platform: 'instagram',
    handle: 'skyzone_toronto',
    displayName: 'Sky Zone Toronto',
    city: 'Toronto',
    region: 'toronto',
    category: 'T5',
    fsa: null,
    sourceUrl: 'https://mykidspass.online/kids-activity-directory/',
    active: true,
    note: 'Kids Pass directory card linked this handle on 2026-09-27. Card title Sky Zone Toronto.',
  },
  {
    platform: 'instagram',
    handle: 'adventurealleytoronto',
    displayName: 'Adventure Alley',
    city: 'Toronto',
    region: 'toronto',
    category: 'T10',
    fsa: null,
    sourceUrl: 'https://mykidspass.online/kids-activity-directory/',
    active: true,
    note: 'Kids Pass directory card linked this handle on 2026-09-27. Handle names Toronto.',
  },
  {
    platform: 'instagram',
    handle: 'kidnasium_upperbeaches',
    displayName: 'Kidnasium Upper Beaches',
    city: 'Toronto',
    region: 'toronto',
    category: 'T5',
    fsa: null,
    sourceUrl: 'https://mykidspass.online/kids-activity-directory/',
    active: true,
    note: 'Kids Pass directory card linked this handle on 2026-09-27. Upper Beaches is in the handle.',
  },
  {
    platform: 'instagram',
    handle: 'piccolotoronto',
    displayName: 'Piccolo Toronto',
    city: 'Toronto',
    region: 'toronto',
    category: 'T10',
    fsa: null,
    sourceUrl: 'https://mykidspass.online/kids-activity-directory/',
    active: true,
    note: 'Kids Pass directory card linked this handle on 2026-09-27. Card title Piccolo Toronto.',
  },
  {
    platform: 'instagram',
    handle: 'highparkzoo',
    displayName: 'High Park Zoo',
    city: 'Toronto',
    region: 'toronto',
    category: 'T4',
    fsa: null,
    sourceUrl: 'https://mykidspass.online/kids-activity-directory/',
    active: true,
    note: 'Kids Pass directory card linked this handle on 2026-09-27. Card title High Park Zoo.',
  },
  {
    platform: 'instagram',
    handle: 'happykingdom_lawrence',
    displayName: 'Happy Kingdom Lawrence',
    city: 'Toronto',
    region: 'toronto',
    category: 'T10',
    fsa: null,
    sourceUrl: 'https://mykidspass.online/kids-activity-directory/',
    active: true,
    note: 'Kids Pass directory card linked this handle on 2026-09-27. Card title Happy Kingdom Lawrence.',
  },
  {
    platform: 'instagram',
    handle: 'happy_kingdom_sheppard',
    displayName: 'Happy Kingdom Sheppard',
    city: 'Toronto',
    region: 'toronto',
    category: 'T10',
    fsa: null,
    sourceUrl: 'https://mykidspass.online/kids-activity-directory/',
    active: true,
    note: 'Kids Pass directory card linked this handle on 2026-09-27. Same handle is linked from the Sheppard and Stockyards cards.',
  },
  {
    platform: 'instagram',
    handle: 'jfcf.centre',
    displayName: 'Jane Finch Centre',
    city: 'Toronto',
    region: 'toronto',
    category: 'T1',
    fsa: null,
    sourceUrl: 'https://www.janefinchcentre.org/',
    active: true,
    note: 'Homepage linked jfcf.centre. The janefinch_earlyon handle from the competitor list was not on this page.',
  },
  {
    platform: 'instagram',
    handle: 'playciousmississauga',
    displayName: 'Playcious Mississauga',
    city: 'Mississauga',
    region: 'peel',
    category: 'T10',
    fsa: null,
    sourceUrl: 'https://mykidspass.online/kids-activity-directory/',
    active: true,
    note: 'Kids Pass directory card linked this handle on 2026-09-27. Card title Playcious Mississauga.',
  },
  {
    platform: 'instagram',
    handle: 'happykingdom_brampton',
    displayName: 'Happy Kingdom Brampton',
    city: 'Brampton',
    region: 'peel',
    category: 'T10',
    fsa: null,
    sourceUrl: 'https://mykidspass.online/kids-activity-directory/',
    active: true,
    note: 'Kids Pass directory card linked this handle on 2026-09-27. Card title Happy Kingdom Brampton.',
  },
  {
    platform: 'instagram',
    handle: 'activategames',
    displayName: 'Activate Mississauga',
    city: 'Mississauga',
    region: 'peel',
    category: 'T5',
    fsa: null,
    sourceUrl: 'https://mykidspass.online/kids-activity-directory/',
    active: true,
    note: 'Kids Pass directory card linked this handle on 2026-09-27. Card title Activate Mississauga.',
  },
  {
    platform: 'instagram',
    handle: 'themightyjunglemississauga',
    displayName: 'The Mighty Jungle',
    city: 'Mississauga',
    region: 'peel',
    category: 'T10',
    fsa: null,
    sourceUrl: 'https://mykidspass.online/kids-activity-directory/',
    active: true,
    note: 'Kids Pass directory card linked this handle on 2026-09-27. Handle names Mississauga.',
  },
  {
    platform: 'instagram',
    handle: 'citymississauga',
    displayName: 'City of Mississauga',
    city: 'Mississauga',
    region: 'peel',
    category: 'T9',
    fsa: null,
    sourceUrl: 'https://www.mississauga.ca/',
    active: true,
    note: 'City homepage linked this handle. Registration windows, not the season catalog. The catalog stays on the civic and registration rails.',
  },
  {
    platform: 'instagram',
    handle: 'citybrampton',
    displayName: 'City of Brampton',
    city: 'Brampton',
    region: 'peel',
    category: 'T9',
    fsa: null,
    sourceUrl: 'https://www.brampton.ca/',
    active: true,
    note: 'City homepage linked this handle. Registration windows, not the season catalog.',
  },
  {
    platform: 'instagram',
    handle: 'airriderz_vaughan',
    displayName: 'Air Riderz Vaughan',
    city: 'Vaughan',
    region: 'york',
    category: 'T5',
    fsa: null,
    sourceUrl: 'https://mykidspass.online/kids-activity-directory/',
    active: true,
    note: 'Kids Pass directory card linked this handle on 2026-09-27. Card title Air Riderz Vaughan.',
  },
  {
    platform: 'instagram',
    handle: 'gymalayavaughan',
    displayName: 'Gymalaya Vaughan',
    city: 'Vaughan',
    region: 'york',
    category: 'T5',
    fsa: null,
    sourceUrl: 'https://mykidspass.online/kids-activity-directory/',
    active: true,
    note: 'Kids Pass directory card linked this handle on 2026-09-27. Card title Gymalaya Vaughan.',
  },
  {
    platform: 'instagram',
    handle: 'gymalayanewmarket',
    displayName: 'Gymalaya Newmarket',
    city: 'Newmarket',
    region: 'york',
    category: 'T5',
    fsa: null,
    sourceUrl: 'https://mykidspass.online/kids-activity-directory/',
    active: true,
    note: 'Kids Pass directory card linked this handle on 2026-09-27. Card title Gymalaya Newmarket.',
  },
  {
    platform: 'instagram',
    handle: 'junglelandvaughan',
    displayName: 'Jungleland',
    city: 'Vaughan',
    region: 'york',
    category: 'T10',
    fsa: null,
    sourceUrl: 'https://mykidspass.online/kids-activity-directory/',
    active: true,
    note: 'Kids Pass directory card linked this handle on 2026-09-27. Card title is Jungleland. The linked handle is junglelandvaughan.',
  },
  {
    platform: 'instagram',
    handle: 'magicpalace.vaughan',
    displayName: 'Magic Palace',
    city: 'Vaughan',
    region: 'york',
    category: 'T10',
    fsa: null,
    sourceUrl: 'https://mykidspass.online/kids-activity-directory/',
    active: true,
    note: 'Kids Pass directory card linked this handle on 2026-09-27. Handle names Vaughan.',
  },
  {
    platform: 'instagram',
    handle: 'playciousinc',
    displayName: 'Playcious Vaughan',
    city: 'Vaughan',
    region: 'york',
    category: 'T10',
    fsa: null,
    sourceUrl: 'https://mykidspass.online/kids-activity-directory/',
    active: true,
    note: 'Kids Pass directory card linked this handle on 2026-09-27. Card title Playcious Vaughan.',
  },
  {
    platform: 'instagram',
    handle: 'playtropolis_woodbridge',
    displayName: 'Playtropolis',
    city: 'Woodbridge',
    region: 'york',
    category: 'T10',
    fsa: null,
    sourceUrl: 'https://mykidspass.online/kids-activity-directory/',
    active: true,
    note: 'Kids Pass directory card linked this handle on 2026-09-27. Handle names Woodbridge.',
  },
  {
    platform: 'instagram',
    handle: 'tinytownvaughan',
    displayName: 'Tiny Town Vaughan',
    city: 'Vaughan',
    region: 'york',
    category: 'T10',
    fsa: null,
    sourceUrl: 'https://mykidspass.online/kids-activity-directory/',
    active: true,
    note: 'Kids Pass directory card linked this handle on 2026-09-27. Card title Tiny Town Vaughan.',
  },
  {
    platform: 'instagram',
    handle: 'candylandvaughan',
    displayName: 'Candyland Play Vaughan',
    city: 'Vaughan',
    region: 'york',
    category: 'T10',
    fsa: null,
    sourceUrl: 'https://mykidspass.online/kids-activity-directory/',
    active: true,
    note: 'Kids Pass directory card linked this handle on 2026-09-27. Card title Candyland Play Vaughan.',
  },
  {
    platform: 'instagram',
    handle: 'jollybubble_markham',
    displayName: 'The Jolly Bubble Markham',
    city: 'Markham',
    region: 'york',
    category: 'T10',
    fsa: null,
    sourceUrl: 'https://mykidspass.online/kids-activity-directory/',
    active: true,
    note: 'Kids Pass directory card linked this handle on 2026-09-27. Card title The Jolly Bubble Markham.',
  },
  {
    platform: 'instagram',
    handle: 'airriderz_aurora',
    displayName: 'Air Riderz Aurora',
    city: 'Aurora',
    region: 'york',
    category: 'T5',
    fsa: null,
    sourceUrl: 'https://mykidspass.online/kids-activity-directory/',
    active: true,
    note: 'Kids Pass directory card linked this handle on 2026-09-27. Card title Air Riderz Aurora.',
  },
  {
    platform: 'instagram',
    handle: 'oceanloopaurora',
    displayName: 'Ocean Loop',
    city: 'Aurora',
    region: 'york',
    category: 'T10',
    fsa: null,
    sourceUrl: 'https://mykidspass.online/kids-activity-directory/',
    active: true,
    note: 'Kids Pass directory card linked this handle on 2026-09-27. Card links oceanloopaurora.',
  },
  {
    platform: 'instagram',
    handle: 'yorkregiongovt',
    displayName: 'York Region',
    city: 'York Region',
    region: 'york',
    category: 'T9',
    fsa: null,
    sourceUrl: 'https://www.york.ca/',
    active: true,
    note: 'Regional homepage linked this handle. EarlyON and rec news, not a replacement for the civic calendars.',
  },
  {
    platform: 'instagram',
    handle: 'applewoodfarmstouffville',
    displayName: 'Applewood Farm',
    city: 'Stouffville',
    region: 'york',
    category: 'T2',
    fsa: 'L4A',
    sourceUrl: 'https://applewoodfarm.ca/',
    active: true,
    note: 'Farm homepage linked this handle and names Stouffville L4A. The page also says Toronto.',
  },
  {
    platform: 'instagram',
    handle: 'kidz.kornermilton',
    displayName: 'Kidz Korner',
    city: 'Milton',
    region: 'halton',
    category: 'T10',
    fsa: null,
    sourceUrl: 'https://mykidspass.online/kids-activity-directory/',
    active: true,
    note: 'Kids Pass directory card linked this handle on 2026-09-27. Card title is Kidz Korner. The linked handle is kidz.kornermilton.',
  },
  {
    platform: 'instagram',
    handle: 'rockinjumpburlington',
    displayName: 'Rockin Jump Burlington',
    city: 'Burlington',
    region: 'halton',
    category: 'T5',
    fsa: null,
    sourceUrl: 'https://mykidspass.online/kids-activity-directory/',
    active: true,
    note: 'Kids Pass directory card linked this handle on 2026-09-27. Card title Rockin Jump Burlington.',
  },
  {
    platform: 'instagram',
    handle: 'playtopiaburlington',
    displayName: 'Playtopia Burlington',
    city: 'Burlington',
    region: 'halton',
    category: 'T10',
    fsa: null,
    sourceUrl: 'https://mykidspass.online/kids-activity-directory/',
    active: true,
    note: 'Kids Pass directory card linked this handle on 2026-09-27. Card title Playtopia Burlington.',
  },
  {
    platform: 'instagram',
    handle: 'aerosportsoakville',
    displayName: 'AeroSports Oakville',
    city: 'Oakville',
    region: 'halton',
    category: 'T5',
    fsa: null,
    sourceUrl: 'https://mykidspass.online/kids-activity-directory/',
    active: true,
    note: 'Kids Pass directory card linked this handle on 2026-09-27. Card title AeroSports Oakville.',
  },
  {
    platform: 'instagram',
    handle: 'funhq_oakville',
    displayName: 'FUNHQ',
    city: 'Oakville',
    region: 'halton',
    category: 'T14',
    fsa: null,
    sourceUrl: 'https://mykidspass.online/kids-activity-directory/',
    active: true,
    note: 'Kids Pass directory card linked this handle on 2026-09-27. Card title is FUNHQ. The linked handle is funhq_oakville.',
  },
  {
    platform: 'instagram',
    handle: 'wrtsoakville',
    displayName: 'We Rock The Spectrum Oakville',
    city: 'Oakville',
    region: 'halton',
    category: 'T5',
    fsa: null,
    sourceUrl: 'https://mykidspass.online/kids-activity-directory/',
    active: true,
    note: 'Kids Pass directory card linked this handle on 2026-09-27. Card title We Rock The Spectrum Oakville.',
  },
  {
    platform: 'instagram',
    handle: 'townofoakville',
    displayName: 'Town of Oakville',
    city: 'Oakville',
    region: 'halton',
    category: 'T9',
    fsa: null,
    sourceUrl: 'https://www.oakville.ca/',
    active: true,
    note: 'Town homepage linked this handle. Registration windows, not the season catalog.',
  },
  {
    platform: 'instagram',
    handle: 'cityburlington',
    displayName: 'City of Burlington',
    city: 'Burlington',
    region: 'halton',
    category: 'T9',
    fsa: null,
    sourceUrl: 'https://www.burlington.ca/',
    active: true,
    note: 'City homepage linked this handle. Registration windows, not the season catalog.',
  },
  {
    platform: 'instagram',
    handle: 'ggajax',
    displayName: 'Glama Gal Ajax',
    city: 'Ajax',
    region: 'durham',
    category: 'T6',
    fsa: null,
    sourceUrl: 'https://mykidspass.online/kids-activity-directory/',
    active: true,
    note: 'Kids Pass directory card linked this handle on 2026-09-27. Card title Glama Gal Ajax.',
  },
  {
    platform: 'instagram',
    handle: 'splatterroomoshawa',
    displayName: 'Splatter Room Oshawa',
    city: 'Oshawa',
    region: 'durham',
    category: 'T6',
    fsa: null,
    sourceUrl: 'https://mykidspass.online/kids-activity-directory/',
    active: true,
    note: 'Kids Pass directory card linked this handle on 2026-09-27. Card title Splatter Room Oshawa.',
  },
  {
    platform: 'instagram',
    handle: 'bloomandgrowbrooklin',
    displayName: 'Bloom and Grow Play Space',
    city: 'Brooklin',
    region: 'durham',
    category: 'T10',
    fsa: null,
    sourceUrl: 'https://mykidspass.online/kids-activity-directory/',
    active: true,
    note: 'Kids Pass directory card linked this handle on 2026-09-27. Handle names Brooklin, in Whitby.',
  },
  {
    platform: 'instagram',
    handle: 'townofajax',
    displayName: 'Town of Ajax',
    city: 'Ajax',
    region: 'durham',
    category: 'T9',
    fsa: null,
    sourceUrl: 'https://www.ajax.ca/',
    active: true,
    note: 'Town homepage linked this handle. Registration windows, not the season catalog.',
  },
  {
    platform: 'instagram',
    handle: 'theregionofdurham',
    displayName: 'Region of Durham',
    city: 'Durham',
    region: 'durham',
    category: 'T9',
    fsa: null,
    sourceUrl: 'https://www.durham.ca/',
    active: true,
    note: 'Regional homepage linked this handle. EarlyON and rec news, not a replacement for the civic calendars.',
  },
  {
    platform: 'instagram',
    handle: 'stepxstepclub',
    displayName: 'S Town Club Pickering',
    city: 'Pickering',
    region: 'durham',
    category: 'T10',
    fsa: null,
    sourceUrl: 'https://mykidspass.online/kids-activity-directory/',
    active: true,
    note: 'Kids Pass directory card linked this handle on 2026-09-27. Card title S Town Club Pickering.',
  },
  {
    platform: 'instagram',
    handle: 'planetgymnasticsdurham',
    displayName: 'Planet Gymnastics',
    city: 'Pickering',
    region: 'durham',
    category: 'T5',
    fsa: null,
    sourceUrl: 'https://planetgymnastics.ca/',
    active: true,
    note: 'Homepage linked this handle and names Pickering and Whitby.',
  },
  {
    platform: 'instagram',
    handle: 'applegrove_earlyon',
    displayName: 'Applegrove EarlyON',
    city: 'Toronto',
    region: 'toronto',
    category: 'T1',
    fsa: null,
    sourceUrl: 'https://www.applegrove.org/earlyon/',
    active: false,
    note: 'EarlyON page fetched 2026-09-27 did not link this handle. Named in the 2026-09-27 competitor seed list. Not confirmed on a venue or directory card that also names the city. Left inactive.',
  },
  {
    platform: 'instagram',
    handle: 'janefinch_earlyon',
    displayName: 'Jane Finch EarlyON',
    city: 'Toronto',
    region: 'toronto',
    category: 'T1',
    fsa: null,
    sourceUrl: 'https://www.janefinchcentre.org/',
    active: false,
    note: 'The Jane Finch Centre homepage links jfcf.centre, not this handle. Named in the 2026-09-27 competitor seed list. Not confirmed on a venue or directory card that also names the city. Left inactive.',
  },
  {
    platform: 'instagram',
    handle: 'georgehull.earlyon',
    displayName: 'George Hull EarlyON',
    city: 'Toronto',
    region: 'toronto',
    category: 'T1',
    fsa: null,
    sourceUrl: 'https://georgehullcentre.ca/',
    active: false,
    note: 'Homepage fetched 2026-09-27 did not link this handle. Named in the 2026-09-27 competitor seed list. Not confirmed on a venue or directory card that also names the city. Left inactive.',
  },
  {
    platform: 'instagram',
    handle: '30college_earlyon',
    displayName: '30 College EarlyON',
    city: 'Toronto',
    region: 'toronto',
    category: 'T1',
    fsa: null,
    sourceUrl: 'https://www.nativechild.org/',
    active: false,
    note: 'Not on the Native Child homepage that links nativechildoftoronto. Named in the 2026-09-27 competitor seed list. Not confirmed on a venue or directory card that also names the city. Left inactive.',
  },
  {
    platform: 'instagram',
    handle: 'pinglesfarm',
    displayName: 'Pingle\'s Farm',
    city: 'Hampton',
    region: 'durham',
    category: 'T2',
    fsa: null,
    sourceUrl: 'https://mykidspass.online/kids-activity-directory/',
    active: false,
    note: 'Kids Pass directory card linked this handle on 2026-09-27. Card title does not name a city. Competitor note places it in Hampton. Left inactive.',
  },
  {
    platform: 'instagram',
    handle: 'roundsranch',
    displayName: 'Rounds Ranch',
    city: null,
    region: 'durham',
    category: 'T2',
    fsa: null,
    sourceUrl: 'https://roundsranch.com/',
    active: false,
    note: 'Homepage links this handle. Visible text did not name a city; a rural L0L code appeared. Left inactive.',
  },
  {
    platform: 'instagram',
    handle: 'kidzfuncentre',
    displayName: 'Kidz Fun Centre',
    city: null,
    region: 'durham',
    category: 'T10',
    fsa: null,
    sourceUrl: 'https://mykidspass.online/kids-activity-directory/',
    active: false,
    note: 'Kids Pass directory card linked this handle on 2026-09-27. Card does not name a city. Competitor note says Ajax area. Left inactive.',
  },
  {
    platform: 'instagram',
    handle: 'playislandexplorers',
    displayName: 'Play Island Explorers',
    city: 'Richmond Hill',
    region: 'york',
    category: 'T10',
    fsa: null,
    sourceUrl: 'https://mykidspass.online/kids-activity-directory/',
    active: false,
    note: 'Not on the Kids Pass directory fetch. Named in the 2026-09-27 competitor seed list. Not confirmed on a venue or directory card that also names the city. Left inactive.',
  },
  {
    platform: 'instagram',
    handle: 'kidzworld_richmondhill',
    displayName: 'Kidz World Richmond Hill',
    city: 'Richmond Hill',
    region: 'york',
    category: 'T10',
    fsa: null,
    sourceUrl: 'https://mykidspass.online/kids-activity-directory/',
    active: false,
    note: 'Not on the Kids Pass directory fetch. Named in the 2026-09-27 competitor seed list. Not confirmed on a venue or directory card that also names the city. Left inactive.',
  },
  {
    platform: 'instagram',
    handle: 'little_goobers_',
    displayName: 'Little Goobers',
    city: 'Burlington',
    region: 'halton',
    category: 'T10',
    fsa: null,
    sourceUrl: 'https://mykidspass.online/kids-activity-directory/',
    active: false,
    note: 'Kids Pass directory card linked this handle on 2026-09-27. Card title does not name a city. Competitor note places it in Burlington. Left inactive.',
  },
  {
    platform: 'instagram',
    handle: 'playtopiagta',
    displayName: 'Playtopia GTA',
    city: 'Halton',
    region: 'halton',
    category: 'T10',
    fsa: null,
    sourceUrl: 'https://mykidspass.online/kids-activity-directory/',
    active: false,
    note: 'Not on the Kids Pass directory fetch. Playtopia Burlington is a separate verified handle. Named in the 2026-09-27 competitor seed list. Not confirmed on a venue or directory card that also names the city. Left inactive.',
  },
  {
    platform: 'instagram',
    handle: 'bramptonparksrec',
    displayName: 'Brampton Parks and Rec',
    city: 'Brampton',
    region: 'peel',
    category: 'T9',
    fsa: null,
    sourceUrl: 'https://www.brampton.ca/',
    active: false,
    note: 'Brampton homepage linked citybrampton, not this handle. Named in the 2026-09-27 competitor seed list. Not confirmed on a venue or directory card that also names the city. Left inactive.',
  },
];

/** Official pages and a public directory. No row is a scrape. */
export const SOCIAL_SEED_TOS_RISK = 'official' as const;

export function profileUrlFor(source: SocialSeedSource): string {
  if (source.platform === 'instagram') return `https://www.instagram.com/${source.handle}/`;
  if (source.platform === 'facebook_page') return `https://www.facebook.com/${source.handle}`;
  return source.sourceUrl;
}
